#!/usr/bin/env python3
"""Capture the block ids the HF 16-17 dynamic coinbase unlock rule reads.

`specs/15-testing-and-conformance.md` §3.2: "**Coinbase unlock time.** For the
HF 16-17 range, assert your `pod_to_hex(...)[..3]` reading matches the C++ for
at least 100 real blocks -- this is the rule most likely to be implemented as a
byte-swap by mistake."

For a block at height `h` in HF 16-17 the C++ computes

    N        = 1337 on mainnet, 5 elsewhere
    blk_id   = get_block_id_by_height(h - N)
    hex3     = pod_to_hex(blk_id)[0:3]            # storage order, lowercase
    unlock   = h + 2 * int(hex3, 16) + 288

The coinbase `unlock_time` itself is already in the block corpus
(`tests/corpus/blocks/mainnet/index.tsv`), so all that is missing is the id of
the block 1337 back. This fetches exactly those, for the corpus heights that
fall inside HF 16-17 (253,999 .. 331,169).

Output: `tests/corpus/unlock/mainnet.tsv`

    height \t ref_height \t ref_block_id

Usage:
    python scripts/fetch-unlock.py --daemon 127.0.0.1:34568
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import time
import urllib.error
import urllib.request

# `mainnet_hard_forks`: HF 16 at 253,999, HF 18 at 331,170.
HF16_HEIGHT = 253_999
HF18_HEIGHT = 331_170
MAINNET_LOOKBACK = 1337


class Daemon:
    def __init__(self, addr: str, timeout: float = 60.0):
        self.url = f"http://{addr}/json_rpc"
        self.timeout = timeout

    def rpc(self, method: str, params: dict | None = None, retries: int = 6) -> dict:
        body = json.dumps(
            {"jsonrpc": "2.0", "id": "0", "method": method, "params": params or {}}
        ).encode()
        last = None
        for attempt in range(retries):
            try:
                req = urllib.request.Request(
                    self.url, body, {"Content-Type": "application/json"}
                )
                with urllib.request.urlopen(req, timeout=self.timeout) as r:
                    out = json.load(r)
                if "error" in out:
                    raise RuntimeError(f"{method}: {out['error']}")
                return out["result"]
            except (urllib.error.URLError, TimeoutError, json.JSONDecodeError) as e:
                last = e
                time.sleep(min(2**attempt, 30))
        raise RuntimeError(f"{method} failed after {retries} tries: {last}")

    def block_id(self, height: int) -> str:
        return self.rpc("get_block_header_by_height", {"height": height})[
            "block_header"
        ]["hash"]


def corpus_heights(path: str) -> list[int]:
    heights = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            heights.append(int(line.split("\t", 1)[0]))
    return sorted(set(heights))


def main() -> int:
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--daemon", default="127.0.0.1:34568")
    ap.add_argument(
        "--corpus",
        default=os.path.join(root, "tests", "corpus", "blocks", "mainnet", "index.tsv"),
    )
    ap.add_argument(
        "--out",
        default=os.path.join(root, "tests", "corpus", "unlock", "mainnet.tsv"),
    )
    ap.add_argument(
        "--limit",
        type=int,
        default=400,
        help="how many heights to capture (§3.2 asks for at least 100)",
    )
    args = ap.parse_args()

    if not os.path.exists(args.corpus):
        print(
            f"no block corpus at {args.corpus}; run scripts/fetch-corpus.py first",
            file=sys.stderr,
        )
        return 1

    in_range = [h for h in corpus_heights(args.corpus) if HF16_HEIGHT <= h < HF18_HEIGHT]
    if len(in_range) < 100:
        print(
            f"only {len(in_range)} corpus blocks in HF 16-17; §3.2 wants 100+."
            " Re-run scripts/fetch-corpus.py with a larger --per-era.",
            file=sys.stderr,
        )
    # Spread the sample across the range rather than taking a prefix, so both
    # forks and both ends are represented.
    if len(in_range) > args.limit:
        step = len(in_range) / args.limit
        in_range = [in_range[int(i * step)] for i in range(args.limit)]

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    # Write to `.part` and rename at the end, so a reader can tell a fetch in
    # progress from a finished one -- the Rust test relaxes its coverage
    # assertions for the former rather than failing on a short corpus.
    tmp = args.out + ".part"
    t0 = time.time()
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write("# height\tref_height\tref_block_id\n")
        f.write(
            f"# generated by scripts/fetch-unlock.py from {args.daemon};"
            f" ref_height = height - {MAINNET_LOOKBACK}\n"
        )
        for i, h in enumerate(in_range):
            ref = h - MAINNET_LOOKBACK
            f.write(f"{h}\t{ref}\t{d_block_id(args, ref)}\n")
            f.flush()
            if (i + 1) % 25 == 0:
                print(
                    f"{time.strftime('%H:%M:%S')}  {i + 1}/{len(in_range)}"
                    f"  {time.time() - t0:.0f}s",
                    file=sys.stderr,
                    flush=True,
                )

    os.replace(tmp, args.out)
    print(f"wrote {args.out} ({len(in_range)} heights)")
    return 0


_daemon: Daemon | None = None


def d_block_id(args, height: int) -> str:
    global _daemon
    if _daemon is None:
        _daemon = Daemon(args.daemon)
    return _daemon.block_id(height)


if __name__ == "__main__":
    raise SystemExit(main())
