//! Round-trip and hash conformance — the M1 gate for `wow-types`.
//!
//! `specs/15-testing-and-conformance.md` §2.2:
//!
//! ```text
//! assert serialize(parse(block_blob)) == block_blob
//! assert block_id(parsed) == known hash
//! assert tx_hash(parsed.miner_tx) == known hash
//! assert merkle_root(parsed) == the value in the hashing blob
//! assert sig_data(parsed) == the C++ get_sig_data output   (HF >= 18 blocks)
//! ```
//!
//! "The re-serialization check catches non-canonical varints, missed
//! conditional fields and wrong array-length derivations in one line."
//!
//! The full gate wants ~10,000 mainnet blocks spread across all hard-fork eras.
//! That corpus is generated by `scripts/fetch-corpus.py` against a synced
//! daemon and dropped into `tests/corpus/blocks/mainnet/`; when it is absent
//! these tests fall back to what can be validated offline:
//!
//! * the genesis transaction of all three networks, from `specs/01` §2.2,
//! * the block and transaction blobs vendored from the reference tree's fuzz
//!   corpora and `tests/data/txs`,
//! * synthetic coverage of every structural variant the format admits.

use std::collections::BTreeMap;
use std::path::PathBuf;

use wow_crypto::hex;
use wow_serialize::binary::Writer;
use wow_types::block::Block;
use wow_types::hashes::transaction_hash_from_blob;
use wow_types::rct::RctType;
use wow_types::tx::Transaction;

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/corpus")
}

/// `serialize(parse(blob)) == blob`, the single most valuable assertion here.
fn assert_block_roundtrips(blob: &[u8], what: &str) -> Block {
    let b = Block::from_blob(blob).unwrap_or_else(|e| panic!("{what}: parse failed: {e}"));
    let mut w = Writer::new();
    b.write(&mut w);
    assert_eq!(
        hex::encode(w.as_slice()),
        hex::encode(blob),
        "{what}: re-serialization differs"
    );
    b
}

fn assert_tx_roundtrips(blob: &[u8], what: &str) -> Transaction {
    let tx = Transaction::from_blob(blob).unwrap_or_else(|e| panic!("{what}: parse failed: {e}"));
    let mut w = Writer::new();
    tx.write(&mut w);
    assert_eq!(
        hex::encode(w.as_slice()),
        hex::encode(blob),
        "{what}: re-serialization differs"
    );

    // The recorded offsets must partition the blob exactly.
    assert!(
        tx.prefix_size <= tx.unprunable_size,
        "{what}: offsets inverted"
    );
    assert!(
        tx.unprunable_size <= blob.len(),
        "{what}: offsets past the blob"
    );
    tx
}

// ---------------------------------------------------------------------------
// Genesis
// ---------------------------------------------------------------------------

/// `specs/01-constants.md` §2.2. The genesis coinbase for each network, as a
/// hex `GENESIS_TX`.
const GENESIS_TX: [(&str, &str); 3] = [
    (
        "mainnet",
        "013c01ff0001ffffffffff1f029b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f5142ee494ffbbd08807121012a1a936be5d91c01ee876e38c13fab0ee11cbe86011a2bf7740fb5ebd39d267d",
    ),
    (
        "testnet",
        "013c01ff0001ffffffffffff03029b2e4c0281c0b02e7c53291a94d1d0cbff8883f8024f5142ee494ffbbd08807121017767aafcde9be00dcfd098715ebcf7f410daebc582fda69d24a28e9d0bc890d1",
    ),
    (
        "stagenet",
        "013c01ff0001ffffffffffff0302df5d56da0c7d643ddd1ce61901c7bdc5fb1738bfe39fbe69c28a3a7032729c0f2101168d0c4ca86fb55a4cf6a36d31431be1c53a3bd7411bb24e8832410289fa6f3b",
    ),
];

/// The genesis coinbase must parse and re-serialize byte-for-byte, on all three
/// networks. It is v1, so the hash is over the whole blob.
#[test]
fn genesis_transactions_roundtrip() {
    for (net, hexstr) in GENESIS_TX {
        let blob = hex::decode(hexstr).expect("genesis hex");
        let tx = assert_tx_roundtrips(&blob, net);

        assert_eq!(tx.prefix.version, 1, "{net}: genesis is a v1 transaction");
        assert!(tx.prefix.is_miner_tx(), "{net}: genesis is a coinbase");
        assert_eq!(tx.prefix.vout.len(), 1, "{net}: one output");
        assert_eq!(tx.prefix.unlock_time, 60, "{net}: 60-block coinbase lock");

        // v1 coinbase -> a txin_gen at height 0, and no ring signatures.
        match &tx.prefix.vin[0] {
            wow_types::tx::TxIn::Gen { height } => assert_eq!(*height, 0),
            other => panic!("{net}: genesis input is {other:?}"),
        }
        // One row per input, each empty: a txin_gen has no signatures.
        assert_eq!(tx.signatures.len(), tx.prefix.vin.len());
        assert!(tx.signatures.iter().all(|r| r.is_empty()));

        // A v1 tx hashes over its whole blob.
        let h = transaction_hash_from_blob(&tx, &blob).unwrap();
        assert_eq!(h, wow_crypto::cn_fast_hash(&blob), "{net}");
    }
}

/// Constructing the genesis block per `specs/01` §2.2 and checking its shape.
///
/// `major_version = 7` is below `HF_VERSION_BLOCK_HEADER_MINER_SIG`, so the
/// header carries **no** `signature` and **no** `vote` — the single most
/// important conditional field in the format.
#[test]
fn genesis_block_has_no_signature_or_vote() {
    let blob = hex::decode(GENESIS_TX[0].1).unwrap();
    let miner_tx = Transaction::from_blob(&blob).unwrap();

    let block = Block {
        header: wow_types::block::BlockHeader {
            major_version: 7,
            minor_version: 7,
            timestamp: 0,
            prev_id: [0u8; 32],
            nonce: 70, // GENESIS_NONCE, mainnet
            signature: Default::default(),
            vote: 0,
        },
        miner_tx,
        tx_hashes: Vec::new(),
    };

    assert!(!block.header.has_miner_signature());
    let serialized = block.to_blob();
    let reparsed = assert_block_roundtrips(&serialized, "genesis");
    assert_eq!(reparsed, block);

    // The hashing blob ends with varint(tx_count + 1) = varint(1).
    let hb = block.hashing_blob().unwrap();
    assert_eq!(*hb.last().unwrap(), 1u8);
    // ...and it is header || 32-byte root || that varint.
    let mut hw = Writer::new();
    block.header.write(&mut hw);
    assert_eq!(hb.len(), hw.len() + 32 + 1);

    // With one transaction the Merkle root is the coinbase hash itself.
    assert_eq!(
        block.tx_tree_hash().unwrap(),
        wow_types::hashes::transaction_hash(&block.miner_tx).unwrap()
    );

    // sig_data is undefined below HF 18.
    assert_eq!(block.sig_data(), None);
}

// ---------------------------------------------------------------------------
// The vendored reference corpora
// ---------------------------------------------------------------------------

fn read_corpus(sub: &str) -> Vec<(String, Vec<u8>)> {
    let dir = corpus_dir().join(sub);
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(&dir) else {
        return out;
    };
    let mut paths: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.is_file() && p.extension().map_or(true, |e| e != "md"))
        .collect();
    paths.sort();
    for p in paths {
        if let Ok(b) = std::fs::read(&p) {
            out.push((p.file_name().unwrap().to_string_lossy().into_owned(), b));
        }
    }
    out
}

#[test]
fn reference_block_corpus_roundtrips() {
    let blocks = read_corpus("blocks");
    assert!(!blocks.is_empty(), "no block corpus found");
    for (name, blob) in blocks {
        let b = assert_block_roundtrips(&blob, &name);
        // Every parsed block must produce a block id and a Merkle root.
        assert!(b.block_id().is_some(), "{name}: no block id");
        assert!(b.tx_tree_hash().is_some(), "{name}: no Merkle root");
        // sig_data exists exactly when the header carries a signature.
        assert_eq!(
            b.sig_data().is_some(),
            b.header.has_miner_signature(),
            "{name}: sig_data presence"
        );
    }
}

#[test]
fn reference_transaction_corpus_roundtrips() {
    let txs = read_corpus("txs");
    assert!(!txs.is_empty(), "no transaction corpus found");
    for (name, blob) in txs {
        let tx = assert_tx_roundtrips(&blob, &name);
        assert!(
            transaction_hash_from_blob(&tx, &blob).is_some(),
            "{name}: no hash"
        );
    }
}

/// `foreign/bpp_tx_e89415.bin` is a **Monero** mainnet transaction that the
/// Wownero tree inherited as test data. It MUST NOT parse as Wownero.
///
/// The two chains number their RingCT types differently: Wownero inserted
/// `FullBulletproof = 3` and `SimpleBulletproof = 4`, shifting everything after
/// them, so Monero's `BulletproofPlus = 6` is Wownero's `Bulletproof2 = 6`. The
/// two layouts disagree and the blob runs out of input.
///
/// Worth pinning: silently accepting a foreign transaction because a type byte
/// happens to be in range is exactly how a cross-chain replay bug starts.
#[test]
fn a_monero_bulletproof_plus_tx_is_not_a_wownero_one() {
    let path = corpus_dir().join("foreign/bpp_tx_e89415.bin");
    let blob = std::fs::read(&path).expect("foreign/bpp_tx_e89415.bin");

    // The prefix format is shared, so it parses; the type byte follows it.
    let mut r = wow_serialize::binary::Reader::new(&blob);
    let prefix = wow_types::tx::TransactionPrefix::read(&mut r).expect("the prefix is shared");
    assert_eq!(prefix.version, 2);
    assert_eq!(prefix.vin.len(), 1);
    assert_eq!(prefix.vout.len(), 2);
    // Monero v15 outputs are tagged keys -- the same tag as Wownero HF 20.
    assert_eq!(prefix.vout[0].target.tag(), 0x03);

    let ty = blob[r.pos()];
    assert_eq!(ty, 6, "Monero BulletproofPlus is 6");
    assert_eq!(
        RctType::from_u8(ty).unwrap(),
        RctType::Bulletproof2,
        "the same byte means Bulletproof2 on Wownero"
    );

    assert!(
        Transaction::from_blob(&blob).is_err(),
        "a Monero BP+ transaction must not parse as Wownero"
    );
}

/// Every structural variant the format admits, round-tripped.
///
/// This stands in for the mainnet corpus on the axes a synthetic blob can
/// cover: the conditional header fields, both output target types, and each
/// RingCT type's `rctSigPrunable` layout. It does **not** substitute for real
/// chain data, which is the only thing that validates the hashes.
#[test]
fn synthetic_structural_coverage() {
    use wow_crypto::types::{EcPoint, EcScalar, KeyImage, PublicKey, Signature, ViewTag};
    use wow_types::block::BlockHeader;
    use wow_types::rct::{
        Bulletproof, BulletproofPlus, Clsag, EcdhInfo, MgSig, RangeSig, RctSignatures,
    };
    use wow_types::tx::{TransactionPrefix, TxIn, TxOut, TxOutTarget};

    let pt = |n: u8| EcPoint([n; 32]);
    let sc = |n: u8| EcScalar([n; 32]);

    for &ty in &[
        RctType::Null,
        RctType::Full,
        RctType::Simple,
        RctType::FullBulletproof,
        RctType::SimpleBulletproof,
        RctType::Bulletproof,
        RctType::Bulletproof2,
        RctType::Clsag,
        RctType::BulletproofPlus,
        RctType::BulletproofPlusFullCommit,
    ] {
        let inputs = 2usize;
        let outputs = 2usize;
        let ring = 22usize; // Wownero's fixed ring size at HF >= 9
        let mixin = ring - 1;

        let prefix = TransactionPrefix {
            version: 2,
            unlock_time: 0,
            vin: (0..inputs)
                .map(|i| TxIn::ToKey {
                    amount: 0,
                    key_offsets: (0..ring).map(|j| (j as u64) + 1).collect(),
                    k_image: KeyImage([(i as u8) + 1; 32]),
                })
                .collect(),
            vout: (0..outputs)
                .map(|i| TxOut {
                    amount: 0,
                    target: if i % 2 == 0 {
                        TxOutTarget::ToKey {
                            key: PublicKey([0x10 + i as u8; 32]),
                        }
                    } else {
                        // The HF 20 tagged form.
                        TxOutTarget::ToTaggedKey {
                            key: PublicKey([0x20 + i as u8; 32]),
                            view_tag: ViewTag(0x5a),
                        }
                    },
                })
                .collect(),
            extra: vec![0x01; 33],
        };

        let mut rv = RctSignatures {
            ty,
            txn_fee: if ty.is_null() { 0 } else { 123_456_789 },
            ..Default::default()
        };
        if !ty.is_null() {
            if ty == RctType::Simple {
                rv.pseudo_outs_base = (0..inputs).map(|i| pt(0x30 + i as u8)).collect();
            }
            rv.ecdh_info = (0..outputs)
                .map(|i| {
                    if ty.has_short_ecdh() {
                        let mut a = EcScalar::ZERO;
                        a.0[..8].copy_from_slice(&[i as u8; 8]);
                        EcdhInfo {
                            mask: EcScalar::ZERO,
                            amount: a,
                        }
                    } else {
                        EcdhInfo {
                            mask: sc(0x40 + i as u8),
                            amount: sc(0x50 + i as u8),
                        }
                    }
                })
                .collect();
            rv.out_pk = (0..outputs).map(|i| pt(0x60 + i as u8)).collect();

            let bp = |n: usize| Bulletproof {
                l: (0..n).map(|i| pt(0x70 + i as u8)).collect(),
                r: (0..n).map(|i| pt(0x80 + i as u8)).collect(),
                ..Default::default()
            };
            match ty {
                RctType::SimpleBulletproof | RctType::FullBulletproof => {
                    rv.bulletproofs = (0..outputs).map(|_| bp(7)).collect();
                }
                RctType::BulletproofPlus | RctType::BulletproofPlusFullCommit => {
                    rv.bulletproofs_plus = vec![BulletproofPlus {
                        l: (0..7).map(|i| pt(0x70 + i as u8)).collect(),
                        r: (0..7).map(|i| pt(0x80 + i as u8)).collect(),
                        ..Default::default()
                    }];
                }
                RctType::Bulletproof | RctType::Bulletproof2 | RctType::Clsag => {
                    rv.bulletproofs = vec![bp(7)];
                }
                RctType::Full | RctType::Simple => {
                    rv.range_sigs = (0..outputs).map(|_| RangeSig::default()).collect();
                }
                RctType::Null => {}
            }

            if ty.is_clsag() {
                rv.clsags = (0..inputs)
                    .map(|i| Clsag {
                        s: (0..=mixin).map(|j| sc(j as u8)).collect(),
                        c1: sc(0x90 + i as u8),
                        d: pt(0xa0 + i as u8),
                    })
                    .collect();
            } else {
                let simple_family = matches!(
                    ty,
                    RctType::Simple
                        | RctType::Bulletproof
                        | RctType::Bulletproof2
                        | RctType::SimpleBulletproof
                );
                let n_mg = if simple_family { inputs } else { 1 };
                let ss2 = if simple_family { 2 } else { inputs + 1 };
                rv.mgs = (0..n_mg)
                    .map(|i| MgSig {
                        ss: (0..=mixin)
                            .map(|_| (0..ss2).map(|k| sc(k as u8)).collect())
                            .collect(),
                        cc: sc(0xb0 + i as u8),
                    })
                    .collect();
            }

            if matches!(
                ty,
                RctType::SimpleBulletproof
                    | RctType::Bulletproof
                    | RctType::Bulletproof2
                    | RctType::Clsag
                    | RctType::BulletproofPlus
                    | RctType::BulletproofPlusFullCommit
            ) {
                rv.pseudo_outs = (0..inputs).map(|i| pt(0xc0 + i as u8)).collect();
            }
        }

        let tx = Transaction {
            prefix,
            signatures: Vec::new(),
            rct_signatures: rv,
            prefix_size: 0,
            unprunable_size: 0,
        };
        let mut w = Writer::new();
        tx.write(&mut w);
        let blob = w.into_vec();

        let parsed = assert_tx_roundtrips(&blob, &format!("synthetic {ty:?}"));
        assert_eq!(parsed.rct_signatures.ty, ty);
        assert_eq!(parsed.prefix, tx.prefix);
        assert_eq!(parsed.rct_signatures, tx.rct_signatures, "{ty:?}");
        assert!(
            transaction_hash_from_blob(&parsed, &blob).is_some(),
            "{ty:?}: no hash"
        );
    }

    // --- header variants: with and without signature + vote ---
    for major in [7u8, 17, 18, 20] {
        let header = BlockHeader {
            major_version: major,
            minor_version: major,
            timestamp: 1_700_000_000,
            prev_id: [0xab; 32],
            nonce: 0xdead_beef,
            signature: Signature {
                c: EcScalar([0x11; 32]),
                r: EcScalar([0x22; 32]),
            },
            vote: 2,
        };
        let miner_tx = Transaction::from_blob(&hex::decode(GENESIS_TX[0].1).unwrap()).unwrap();
        let block = Block {
            header: header.clone(),
            miner_tx,
            tx_hashes: (0u8..5).map(|i| [i; 32]).collect(),
        };
        let blob = block.to_blob();
        let parsed = assert_block_roundtrips(&blob, &format!("header v{major}"));

        if major >= 18 {
            assert!(parsed.header.has_miner_signature());
            assert_eq!(parsed.header.signature, header.signature);
            assert_eq!(parsed.header.vote, 2);
            assert!(parsed.sig_data().is_some());
            // Zeroing the signature must change sig_data while keeping vote.
            assert_ne!(parsed.sig_data().unwrap(), parsed.block_id().unwrap());
        } else {
            // Below HF 18 neither field is on the wire, so both read back as
            // zero whatever was set before serializing.
            assert!(!parsed.header.has_miner_signature());
            assert_eq!(parsed.header.signature, Signature::ZERO);
            assert_eq!(parsed.header.vote, 0);
            assert_eq!(parsed.sig_data(), None);
        }

        // The hashing blob always ends with varint(tx_count + 1).
        let hb = parsed.hashing_blob().unwrap();
        assert_eq!(*hb.last().unwrap(), 6, "5 tx hashes + the coinbase");
    }
}

// ---------------------------------------------------------------------------
// The full mainnet corpus, when present
// ---------------------------------------------------------------------------

/// Statistics from one pass over a corpus index.
struct CorpusReport {
    checked: usize,
    with_signature: usize,
    verified_signatures: usize,
    by_version: BTreeMap<u8, usize>,
    failures: Vec<String>,
}

/// The committed HF 18+ boundary blocks.
///
/// From HF 18 every header carries a Schnorr signature over `sig_data`, made
/// with the coinbase output's one-time key (`specs/06` §4). Verifying those
/// against real blocks validates `sig_data`, the Schnorr verifier, point
/// decoding, the Merkle root and the parser **against consensus itself** — a
/// stronger check than `specs/15` §2.2's "compare against the C++
/// `get_sig_data` output", and one that needs no daemon at test time.
///
/// See `tests/corpus/blocks/hf18/README.md` for the heights and why they were
/// picked.
#[test]
fn hf18_header_signatures_verify() {
    let index = corpus_dir().join("blocks/hf18/index.tsv");
    let text = std::fs::read_to_string(&index)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", index.display()));
    let r = check_corpus(&text);

    eprintln!(
        "hf18 corpus: {} blocks, {} signed ({} verified), by major_version: {:?}",
        r.checked, r.with_signature, r.verified_signatures, r.by_version
    );
    assert!(
        r.failures.is_empty(),
        "{} of {} blocks failed:\n{}",
        r.failures.len(),
        r.checked,
        r.failures.join("\n")
    );
    assert_eq!(r.checked, 21, "the committed fixture holds 21 blocks");
    assert_eq!(
        r.verified_signatures, 20,
        "20 of the 21 are HF >= 18 and must have a verifying header signature"
    );
    // Both header-changing boundaries are represented.
    for v in [18u8, 19, 20] {
        assert!(
            r.by_version.contains_key(&v),
            "no HF {v} block in the fixture"
        );
    }
}

/// The real M1 gate: ~10,000 mainnet block blobs with their expected hashes.
///
/// Generated by `scripts/fetch-corpus.py`. Skipped with a clear message when
/// the corpus has not been generated, so a fresh checkout still builds.
#[test]
fn mainnet_block_corpus() {
    let dir = corpus_dir().join("blocks/mainnet");
    if !dir.exists() {
        eprintln!(
            "SKIP mainnet_block_corpus: {} not present.\n\
             Generate it with:  python scripts/fetch-corpus.py --daemon <host:port>\n\
             (specs/15 §2.2 -- the M1 gate is not closed until this runs.)",
            dir.display()
        );
        return;
    }

    let index = dir.join("index.tsv");
    let text = std::fs::read_to_string(&index)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", index.display()));
    let r = check_corpus(&text);

    eprintln!(
        "mainnet corpus: {} blocks, {} with a miner signature ({} verified)\n\
         by major_version: {:?}",
        r.checked, r.with_signature, r.verified_signatures, r.by_version
    );
    assert!(
        r.failures.is_empty(),
        "{} of {} blocks failed:\n{}",
        r.failures.len(),
        r.checked,
        r.failures.join("\n")
    );
    assert!(
        r.checked >= 1000,
        "corpus holds only {} blocks; specs/15 §2.2 wants ~10,000",
        r.checked
    );
}

/// One pass over an `index.tsv`, applying every check of `specs/15` §2.2.
fn check_corpus(text: &str) -> CorpusReport {
    let mut checked = 0usize;
    let mut with_signature = 0usize;
    let mut verified_signatures = 0usize;
    let mut by_version: BTreeMap<u8, usize> = BTreeMap::new();
    // Collected rather than asserted one at a time: over ~10k blocks the first
    // failing height is much less informative than the shape of the failures.
    let mut failures: Vec<String> = Vec::new();
    let note = |f: &mut Vec<String>, msg: String| {
        if f.len() < 25 {
            f.push(msg);
        }
    };

    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // height \t block_id \t miner_tx_hash \t blob_hex [\t sig_data_hex]
        let f: Vec<&str> = line.split('\t').collect();
        assert!(
            f.len() >= 4,
            "index.tsv line {}: {} fields",
            lineno + 1,
            f.len()
        );
        let height: u64 = f[0].parse().expect("height");
        let want_id = f[1];
        let want_miner = f[2];
        let blob = hex::decode(f[3]).expect("blob hex");
        let what = format!("height {height}");

        let b = match Block::from_blob(&blob) {
            Ok(b) => b,
            Err(e) => {
                note(&mut failures, format!("{what}: parse failed: {e}"));
                continue;
            }
        };
        checked += 1;
        *by_version.entry(b.header.major_version).or_default() += 1;

        // serialize(parse(blob)) == blob
        let mut w = Writer::new();
        b.write(&mut w);
        if w.as_slice() != &blob[..] {
            note(&mut failures, format!("{what}: re-serialization differs"));
        }

        match b.block_id() {
            Some(id) if hex::encode(&id) == want_id => {}
            Some(id) => note(
                &mut failures,
                format!("{what}: block id {} != {want_id}", hex::encode(&id)),
            ),
            None => note(&mut failures, format!("{what}: no block id")),
        }

        // The coinbase hash, over its own slice of the block blob.
        let mut mw = Writer::new();
        b.miner_tx.write(&mut mw);
        let miner_blob = mw.into_vec();
        match transaction_hash_from_blob(&b.miner_tx, &miner_blob) {
            Some(h) if hex::encode(&h) == want_miner => {}
            Some(h) => note(
                &mut failures,
                format!("{what}: miner tx hash {} != {want_miner}", hex::encode(&h)),
            ),
            None => note(&mut failures, format!("{what}: no miner tx hash")),
        }

        // The Merkle root must be the value embedded in the hashing blob.
        if let (Some(hb), Some(root)) = (b.hashing_blob(), b.tx_tree_hash()) {
            let mut hw = Writer::new();
            b.header.write(&mut hw);
            let at = hw.len();
            if hb[at..at + 32] != root[..] {
                note(&mut failures, format!("{what}: Merkle root"));
            }
        } else {
            note(&mut failures, format!("{what}: no hashing blob"));
        }

        if b.header.has_miner_signature() {
            with_signature += 1;
            let sd = b.sig_data().expect("HF >= 18 always has sig_data");

            // The strongest check available without an instrumented C++ build,
            // and better than one: from HF 18 every header carries a Schnorr
            // signature over sig_data made with the coinbase output's one-time
            // key (`specs/06` §4). Verifying it against consensus validates the
            // sig_data construction, the Schnorr verifier and the parsing all
            // at once -- if any were wrong, real blocks would not verify.
            match b
                .miner_tx
                .prefix
                .vout
                .first()
                .and_then(|o| o.target.public_key())
            {
                Some(p) => {
                    if !wow_crypto::check_signature(&sd, &p, &b.header.signature) {
                        note(
                            &mut failures,
                            format!("{what}: header signature does not verify"),
                        );
                    } else {
                        verified_signatures += 1;
                    }
                }
                None => note(&mut failures, format!("{what}: no coinbase output key")),
            }
            // `specs/06` §4: exactly one coinbase output from HF 18.
            if b.miner_tx.prefix.vout.len() != 1 {
                note(
                    &mut failures,
                    format!("{what}: {} coinbase outputs", b.miner_tx.prefix.vout.len()),
                );
            }
            // sig_data must differ from the block id: the former zeroes the
            // signature, the latter does not.
            if Some(sd) == b.block_id() {
                note(&mut failures, format!("{what}: sig_data == block id"));
            }
            // vote is consensus-bounded from HF 18.
            if b.header.vote > 2 {
                note(&mut failures, format!("{what}: vote = {}", b.header.vote));
            }
            // Field 5, when present, is the C++ get_sig_data output.
            if let Some(want_sd) = f.get(4).filter(|s| !s.is_empty()) {
                if hex::encode(&sd) != *want_sd {
                    note(&mut failures, format!("{what}: sig_data"));
                }
            }
        }
    }

    CorpusReport {
        checked,
        with_signature,
        verified_signatures,
        by_version,
        failures,
    }
}
