[package]
name = "wow-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
wow-consensus.workspace = true
wow-crypto.workspace = true
wow-randomwow.workspace = true
wow-serialize.workspace = true
wow-storage.workspace = true
wow-types.workspace = true
